version: 2

services:
  - type: web
    name: sunleaf-backend
    env: node
    buildCommand: npm run build --workspace=packages/backend
    startCommand: npm start --workspace=packages/backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: sunleaf-db
    databaseName: sunleaf
    user: sunleaf
